#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

typedef struct node_t node_t;

/**
 * struct node_t - A node of our semantic tree
 * @n_children: Number of children nodes.
 * @yykind: Kind of the node (given by flex / bison).
 * @rule_id: Rule id of node (given by bison), -1 if node is a terminal.
 * @rule_action: Action tag associated with the node.
 * @rule_object: Object tag associated with the node.
 * @rule_order: Order of appearance of the node when parsing.
 * @sem_val: Semantic value associated with the node, NULL if none.
 * @first_child: Pointer to the first child node.
 * @next_brother: Pointer to the next sibling node.
 */
struct node_t
{
    int n_children;
    int yykind;
    int rule_id;
    int rule_action;
    int rule_object;
    int rule_order;
    char *sem_val;
    struct node_t *first_child;
    struct node_t *next_brother;
};

#define GAUR_TAB_MAX_L 10000

/**
 *  Tab servers as a stack of pt nodes until they are given a father
 * - Each shift increments the number of element in the array
 * - Each reduce reduce the number of elements by the number of rhs elements (direct childrens)
 */
node_t *tab[GAUR_TAB_MAX_L];

/**
 * index_tab stores the index of the next available position in the tab
 *  index_tab - 1 corresponds to the index of the last shifted element (when index_tab > 0s)
 */
int index_tab = 0;
int is_collector_error = 0;
int rule_counter = 0;

#define GAUR_PARSE_BEGIN(size, thd) \
    int n_terminal = 0;             \
    int n_nonterminal = 0;          \
    uint64_t ggid = thd->query_id;  \
    index_tab = 0;                  \
    rule_counter = 0;               \
    is_collector_error = 0;

#define GET_ACTION_TAG(i) (ggrulesem[i - 2][0])
#define GET_ASSET_TAG(i) (ggrulesem[i - 2][1])

#define GAUR_ERROR()                                           \
    do                                                         \
    {                                                          \
        collect_and_clean(ggid, n_terminal, n_nonterminal, 1); \
    } while (0);

#define GAUR_SHIFT(yytoken, yytokenvalue)                          \
    do                                                             \
    {                                                              \
        if (yytoken == YYSYMBOL_YYEOF)                             \
            collect_and_clean(ggid, n_terminal, n_nonterminal, 0); \
        else                                                       \
        {                                                          \
            shift(yytoken, yytokenvalue, ggid);                    \
            n_terminal++;                                          \
        }                                                          \
    } while (0);

#define GAUR_REDUCE(nrule, yylen, yykind)                                              \
    do                                                                                 \
    { /* We substract 1 to nrule because of the bison accept rule offset*/             \
        n_nonterminal++;                                                               \
        reduce(yylen, nrule - 1, GET_ASSET_TAG(nrule), GET_ACTION_TAG(nrule), yykind); \
    } while (0)

enum
{
    _CREATE = 1 << 4,
    _DELETE = 1 << 3,
    _EXECUTE = 1 << 2,
    _MODIFY = 1 << 1,
    _READ = 1 << 0,
};

static struct
{
    int value;
    const char *name;
} _actions_mapping[] = {
    {_CREATE, "CREATE"},
    {_DELETE, "DELETE"},
    {_EXECUTE, "EXECUTE"},
    {_MODIFY, "MODIFY"},
    {_READ, "READ"},
};

enum
{
    _TABLESPACE = 1 << 11,
    _TABLE = 1 << 10,
    _INDEX = 1 << 9,
    _VIEW = 1 << 8,
    _USER = 1 << 7,
    _PROCEDURE = 1 << 6,
    _DATABASE = 1 << 5,
    _FUNCTION = 1 << 4,
    _INSTANCE = 1 << 3,
    _LOGFILE = 1 << 2,
    _SERVER = 1 << 1,
    _TRIGGER = 1 << 0,
};

static struct
{
    int value;
    const char *name;
} _assets_mapping[] = {
    {_TABLESPACE, "TABLESPACE"},
    {_TABLE, "TABLE"},
    {_INDEX, "INDEX"},
    {_VIEW, "VIEW"},
    {_USER, "USER"},
    {_PROCEDURE, "PROCEDURE"},
    {_DATABASE, "DATABASE"},
    {_FUNCTION, "FUNCTION"},
    {_INSTANCE, "INSTANCE"},
    {_LOGFILE, "LOGFILE"},
    {_SERVER, "SERVER"},
    {_TRIGGER, "TRIGGER"},
};

/**
 * @brief Called when a shift occurs, we create a node_t object and store it in the tab
 *
 * @param yykind Kind of shifted item (given by flex / bison).
 * @param yyvaluep Pointer to the item semantic value
 * @param ggid Identifier generated by MySQL
 */
void shift(int yykind, YYSTYPE const *const yyvaluep, int ggid)
{
    if (index_tab >= GAUR_TAB_MAX_L || is_collector_error)
    {
        fprintf(stderr, "gaur data collector - shift(): incorrect index_tab: %d for query %d\n", index_tab, ggid);
        is_collector_error = 1;
        return;
    }
    tab[index_tab] = (struct node_t *)malloc(sizeof(struct node_t));
    tab[index_tab]->n_children = 0;
    tab[index_tab]->first_child = NULL;
    tab[index_tab]->next_brother = NULL;
    tab[index_tab]->rule_action = 0;
    tab[index_tab]->rule_object = 0;
    tab[index_tab]->yykind = yykind;
    tab[index_tab]->rule_id = -1;
    tab[index_tab]->rule_order = rule_counter++;

    switch (yykind)
    {
    case YYSYMBOL_TEXT_STRING:
    case YYSYMBOL_IDENT_QUOTED:
    case YYSYMBOL_DECIMAL_NUM:
    case YYSYMBOL_FLOAT_NUM:
    case YYSYMBOL_NUM:
    case YYSYMBOL_LONG_NUM:
    case YYSYMBOL_HEX_NUM:
    case YYSYMBOL_LEX_HOSTNAME:
    case YYSYMBOL_ULONGLONG_NUM:
    case YYSYMBOL_DOLLAR_QUOTED_STRING_SYM:
    case YYSYMBOL_NCHAR_STRING:
    case YYSYMBOL_BIN_NUM:
    {
        tab[index_tab]->sem_val = strdup(yyvaluep->lexer.lex_str.str);
        break;
    }

    // case YYSYMBOL_ident_or_text: -> is a nterm
    // case YYSYMBOL_IDENT_sys: -> is a nterm
    // case YYSYMBOL_TEXT_STRING_sys:-> is a nterm
    // case YYSYMBOL_TEXT_STRING_literal:-> is a nterm
    // case YYSYMBOL_TEXT_STRING_filesystem:-> is a nterm
    // case YYSYMBOL_TEXT_STRING_sys_nonewline: -> is a nterm
    // case YYSYMBOL_TEXT_STRING_password: -> is a nterm
    // case YYSYMBOL_TEXT_STRING_hash:-> is a nterm
    // case YYSYMBOL_TEXT_STRING_validated:-> is a nterm
    default:
    {
        tab[index_tab]->sem_val = NULL;
        break;
    }
    }
    index_tab++;
}

/**
 * @brief Called when a parser reduction occurs, we create a father node_t object, associate it with its children, remove them from tab and store the father in tab.
 *
 * @param n_children Number of rule rhs (number of children to retrieve in tab)
 * @param r_id Rule id (given by bison)
 * @param rule_object Rule object tag
 * @param r_action Rule action tag
 * @param yykind Kind of the node (given by flex / bison)
 */
void reduce(int n_children, int r_id, int rule_object, int r_action, int yykind)
{
    if (is_collector_error) /* Skip reduction if tree is already messed up */
        return;

    node_t *father_node = (struct node_t *)malloc(sizeof(struct node_t));
    father_node->rule_id = r_id;
    father_node->rule_action = r_action;
    father_node->rule_object = rule_object;
    father_node->rule_order = rule_counter++;
    father_node->n_children = n_children;
    father_node->yykind = yykind;
    father_node->sem_val = NULL;

    if (n_children > 0)
    {
        /* We have at least a child: retrieve first node child (tab[index_tab - 1]) */
        index_tab--;
        int remaining_children = n_children - 1; // Store number of remaining children to associate to father.
        father_node->first_child = tab[index_tab];

        node_t *last_children = father_node->first_child; // Store children on which to append next brother

        /* collect n_children last values of array tab and associate them to their father */
        for (int i = 0; i < remaining_children; i++)
        {
            index_tab--;
            if (index_tab < 0 || index_tab >= GAUR_TAB_MAX_L)
            {
                fprintf(stderr, "gaur data collector - reduce(): incorrect index_tab: %d\n", index_tab);

                is_collector_error = 1;
                return;
            }
            last_children->next_brother = tab[index_tab];
            last_children = last_children->next_brother;
        }
    }

    tab[index_tab] = father_node;
    index_tab++;
}

/**
 * @brief Check existence of file, if not exists create it, and create header line, then return file pointer.
 * If already exists, just return file pointer.
 *
 * @return FILE*
 */
FILE *gaur_open_file()
{
    const char *output_name = "gaur.log";
    FILE *f_logs = fopen(output_name, "r");
    if (f_logs == NULL)
    {
        f_logs = fopen(output_name, "w");
        if (f_logs != NULL)
        {
            fprintf(f_logs, "query_id,n_terminal,n_nonterminal,is_syntax_error,semantic_tree,depth\n");
        }
    }
    else
    {
        fclose(f_logs);
        f_logs = fopen(output_name, "a");
    }

    return f_logs;
}

/**
 * @brief Compute the depth of a tree starting from a given node.
 *
 *  Should only be called if input is syntactically valid: the tree is complete
 * @param tree_root
 * @return int Depth of tree.
 */
int get_tree_depth(node_t *tree_root)
{
    if (tree_root == NULL)
        return 0;

    int max = 0;
    int current;

    node_t *next_child = tree_root->first_child;

    for (int i = 0; i < tree_root->n_children; i++)
    {
        current = get_tree_depth(next_child);

        if (current > max)
            max = current;

        next_child = next_child->next_brother;
    }
    return max + 1;
}

/**
 * @brief Function to print additionnal tree features:
 * Depth of the tree
 * @param f
 */
void print_tree_features(FILE *f)
{
    int depth_tree = get_tree_depth(tab[index_tab - 1]);
    fprintf(f, ",%d", depth_tree);
}

/**
 * @brief Print in given file the edges between nodes in the given tree.
 *
 * Each root node edges relations are represented with the following
 * custom format: X>Y:Y':Y''...:  where X is the root node rule order, and Y, Y', Y''...
 * are the rule order of the children of the root node.
 *
 * @param root_node First node of the tree
 * @param f File to output to
 */
void print_edges_relation(node_t *root_node, FILE *f)
{
    /* If root node is null or no children we return */
    if (root_node == NULL || root_node->n_children == 0)
        return;

    fprintf(f, " %d>", root_node->rule_order);
    node_t *current_node = root_node->first_child;
    /* Print edges between root_node and its children. */
    for (int i = 0; i < root_node->n_children; i++)
    {
        fprintf(f, "%d:", current_node->rule_order);
        current_node = current_node->next_brother;
    }
    /* Now iterate over children to display their edges */
    current_node = root_node->first_child;
    for (int i = 0; i < root_node->n_children; i++)
    {
        print_edges_relation(current_node, f);
        current_node = current_node->next_brother;
    }
}

/**
 * @brief Function that makes sure printing the sem_value does not mess with our logfile format
 * - We enclosed the whole semantic tree in double quotes: every occurence of double quotes must be doubled within the string
 * - We also need to make sure no ":" is present, For now we replace them by GAUR_SEMICOLON which is replaced back when post-processing the log file until we find a cleaner way
 * - We also need to make sure no "|" is present
 * @param sem_val
 * @param f
 */
void safe_sem_value_print(char *sem_val, FILE *f)
{
    if (sem_val != NULL)
    {
        for (size_t i = 0; i < strlen(sem_val); i++)
        {
            if (sem_val[i] == '"')
                fprintf(f, "\"\"");
            else if (sem_val[i] == '|')
                fprintf(f, "G_PIPE");
            else if (sem_val[i] == ':')
                fprintf(f, "G_SEMICOLON");
            else
                fprintf(f, "%c", sem_val[i]);
        }
    }
}

/**
 * @brief Print nodes, and their attributes
 *  | appearance_int:symbol_kind:rule_id:action:object:sem_value
 * @param root_node
 * @param f
 */
void print_nodes_attr(node_t *root_node, FILE *f)
{
    // TODO: append all text to a buffer and only print once
    if (root_node == NULL)
        return;

    fprintf(f, "|%d:%d:%d:", root_node->rule_order, root_node->yykind, root_node->rule_id);

    /* Now print action */
    for (size_t i = 0; i < sizeof(_actions_mapping) / sizeof(_actions_mapping[0]); i++)
    {
        if (root_node->rule_action & _actions_mapping[i].value)
        {
            fprintf(f, "%s", _actions_mapping[i].name);
            break;
        }
    }
    fprintf(f, ":");
    for (size_t i = 0; i < sizeof(_assets_mapping) / sizeof(_assets_mapping[0]); i++)
    {
        if (root_node->rule_object & _assets_mapping[i].value)
        {
            fprintf(f, "%s", _assets_mapping[i].name);
            break;
        }
    }
    fprintf(f, ":");
    if (root_node->sem_val != NULL)
    {
        safe_sem_value_print(root_node->sem_val, f);
    }

    node_t *current_node = root_node->first_child;
    for (int i = 0; i < root_node->n_children; i++)
    {
        print_nodes_attr(current_node, f);
        current_node = current_node->next_brother;
    }
}

/**
 * @brief Free the memory allocated for a node and its children
 *
 * @param node Tree node to free
 */
void free_node_and_child(node_t *node)
{
    if (node == NULL)
        return;

    node_t *current_node = node->first_child;
    for (int i = 0; i < node->n_children; i++)
    {
        node_t *next = current_node->next_brother;
        free_node_and_child(current_node);
        current_node = next;
    }

    if (node->sem_val != NULL)
    {
        free(node->sem_val);
    }

    free(node);
}

/**
 * @brief Wrapper for nodes and edges printing
 *
 * @param f
 */
void print_tree_MY(FILE *f)
{
    fprintf(f, ",\"");
    print_nodes_attr(tab[index_tab - 1], f);
    fprintf(f, "||-||"); /* Allows to separate node declaration from edges*/
    print_edges_relation(tab[index_tab - 1], f);
    fprintf(f, "\"");
}

/**
 * @brief Create the log entry corresponding to parsed input and clean the semantic tree data structure
 *
 * @param query_id id to identify query, generated by MySQL
 * @param n_terminal number of terminal nodes in semantic tree
 * @param n_nonterminal number of non-terminal nodes in semantic tree
 * @param is_error presence of syntax error
 */
void collect_and_clean(uint64_t query_id, int n_terminal, int n_nonterminal, int is_error)
{
    FILE *f_logs = gaur_open_file();
    if (f_logs != NULL)
    {
        fprintf(f_logs, "%" PRId64 ",", query_id); /* Print Input ID*/
        fprintf(f_logs, "%d,%d,%d", n_terminal, n_nonterminal, is_error);

        if (is_collector_error)
            fprintf(f_logs, ",,\n"); // One for pt, one for depth
        else
        {
            print_tree_MY(f_logs);
            print_tree_features(f_logs);
            fprintf(f_logs, "\n");
        }
        fclose(f_logs);
    }
    else
    {
        perror("Gaur: Could not open log file.");
    }

    for (int i = 1; i <= index_tab; i++)
    {
        free_node_and_child(tab[index_tab - i]);
        tab[index_tab - i] = NULL;
    }
}
