all:
	@cd sem ; make 
	@cd calc ; make 
	@cd mysql ; make 
clean:
	@cd sem ; make clean
	@cd calc ; make clean
	@cd mysql ; make clean
	@cd mysql-stmts ; make clean
	@cd mysql-claude ; make clean
	@cd mysql-chatgpt ; make clean
